first → txt to dataframe

In [6]:
import pandas as pd

file_path = "all_billionaires.txt"

with open(file_path, "r", encoding="utf-8") as f:
    lines = [line.strip() for line in f if line.strip()]

data = []
i = 0

while i < len(lines):
    try:
        # skip header noise if any
        if not lines[i].isdigit():
            i += 1
            continue

        rank = int(lines[i])
        name = lines[i + 1]
        net_worth = lines[i + 2]

        arrow = lines[i + 3]
        change_amount = lines[i + 4]
        change_percent = lines[i + 5]

        industry = lines[i + 6]
        age = lines[i + 7]
        country = lines[i + 8]

        data.append([
            rank,
            name,
            net_worth,
            arrow,
            change_amount,
            change_percent,
            industry,
            age,
            country
        ])

        i += 9

    except Exception:
        i += 1

columns = [
    "Rank",
    "Name",
    "Net Worth",
    "Change Arrow",
    "Change Amount",
    "Change Percent",
    "Industry",
    "Age",
    "Country"
]

df = pd.DataFrame(data, columns=columns)

print(df.head())

   Rank             Name Net Worth Change Arrow Change Amount Change Percent  \
0     1        Elon Musk   $803.1B            ▲        $2.5 B       | +0.31%
1     2       Larry Page   $263.9B            ▲          $3 B       | +1.13%
2     3       Jeff Bezos   $250.1B            ▲        $1.3 B       | +0.54%
3     4      Sergey Brin   $243.5B            ▲        $2.7 B       | +1.13%
4     5  Mark Zuckerberg   $217.7B            ▲        $1.6 B       | +0.73%

        Industry Age        Country
0  Tesla, SpaceX  54  United States
1         Google  53  United States
2         Amazon  62  United States
3         Google  52  United States
4       Facebook  41  United States

some cleaning

In [15]:
df["Age"] = pd.to_numeric(df["Age"], errors="coerce")

# def convert(value):
#     value = value.replace("$", "")
#     if "B" in value:
#         return float(value.replace("B", "")) * 1_000_000_000
#     if "M" in value:
#         return float(value.replace("M", "")) * 1_000_000
#     return None
#
# df["Net Worth Numeric"] = df["Net Worth"].apply(convert)


df.head(10)

# df.columns


# df = df.drop(columns=[
#     "Change Arrow",
#     "Change Amount",
#     "Change Percent",
#     "Rank"
# ])

                       Name Net Worth           Industry   Age        Country
0                 Elon Musk   $803.1B      Tesla, SpaceX  54.0  United States
1                Larry Page   $263.9B             Google  53.0  United States
2                Jeff Bezos   $250.1B             Amazon  62.0  United States
3               Sergey Brin   $243.5B             Google  52.0  United States
4           Mark Zuckerberg   $217.7B           Facebook  41.0  United States
5             Larry Ellison     $198B             Oracle  81.0  United States
6              Michael Dell     $164B  Dell Technologies  61.0  United States
7              Jensen Huang   $163.9B     Semiconductors  63.0  United States
8  Bernard Arnault & family   $149.1B               LVMH  77.0         France
9       Rob Walton & family     $143B            Walmart  81.0  United States

In [19]:
df.tail(3)


df["Age"] = pd.to_numeric(df["Age"], errors="coerce")

print(f"columns are {df.columns}, no. of rows {df.shape[0]}")

columns are Index(['Name', 'Net Worth', 'Industry', 'Age', 'Country'], dtype='str'), no. of rows 2551

In [21]:
all_b = df["Net Worth"].str.contains("B").all()

print(all_b)

df[~df["Net Worth"].str.contains("B", na=False)]

False

               Name           Net Worth Industry  Age   Country
18    United States       Mukesh Ambani        ▼  NaN  | -2.49%
20           France  Giancarlo Devasini       $0  NaN        61
23    United States        Zhang Yiming       $0  NaN        42
26            China          Robin Zeng        ▲  NaN  | +3.44%
27        Hong Kong      Dieter Schwarz       $0  NaN        86
...             ...                 ...      ...  ...       ...
2543         Brazil             Xi Chao        ▼  NaN  | -2.53%
2544          China       Sung Kyu-dong        ▲  NaN  | +7.46%
2545    South Korea    Jean-Marc Chapus       $0  NaN        67
2547  United States        Eric Ya Shen        ▼  NaN  | -1.76%
2548          China            Tan Lili        ▼  NaN  | -0.76%

[1155 rows x 5 columns]

found that data is badly converted to dataframe